#!/usr/bin/ruby 

require 'rubygems'
require 'hpricot'
require 'open-uri' 
require 'optparse'

class EMusic
	VERSION = '0.5'
	
	def initialize(arguments, stdin)

		# Process the arguments, starting with pulling the filename off the front
		if arguments.size>0
			file = arguments[0]
			options = {}
			OptionParser.new do |opts|
				opts.banner = "Usage: emusic filename [options]"
				opts.on("--version"){output_version; exit 0}
				opts.on("-d directory", "--directory directory", "Save to a specified directory") do |directory|
					options[:directory] = directory
				end
				opts.on("-c directory", "--create directory", "Creates directory and saves to it") do |directory|
					options[:directory] = directory
					options[:force_create] = true
				end
				opts.on("-r", "--remove", "Removes the source file from eMusic after donwloading"){options[:remove] = true}
				opts.on("-v", "--verbose", "Outputs, verbosely"){options[:verbose] = true}
				opts.on_tail("-h", "--help", "Show this message") do
					puts opts
					exit
				end
			end.parse! rescue error
			EMusicUtility.download_media(file, options)
		else
			puts "emusic: Missing source file, use -h switch to see all options"
			exit
		end
	end

	def output_version()
		puts "emusic: version #{VERSION} written by Nicholas Rowe"
	end

	def error
		puts "emusic: Invalid option(s), use -h switch to see all options"
		exit
	end

end


class EMusicUtility

	def EMusicUtility.download_media(filename, options = {})
	# The method that does all of the downloading

		# First, check if the file that we want to download from exists, if it does process it
		if File.exists? filename
			doc = Hpricot.XML(open(filename))

			# If the directory flag isn't set, save the album as ARIST - ALBUM
			if !options[:directory]
				directory = "#{(doc.at("ARTIST")).inner_html} - #{(doc.at("ALBUM")).inner_html}"
				if !File.directory? directory
					FileUtils.mkdir directory
				end

			# If the directory flag is set
			else
				directory = options[:directory]
				if ((options[:force_create] == true) && (!File.directory? directory))
					FileUtils.mkdir directory
				end
			end

			if !File.directory? directory
				puts "emusic: Directory #{directory} not found, use the -D switch to force the creation of it"
				exit 1
			end

			if (options[:verbose] == true)
				puts "emusic: Downloading to: " + directory + "/"
			end

			# download the tracks
			tracks = (doc/:TRACK)

			if tracks.size>0
				tracks.each do |track|
					title = (track/:TITLE).inner_html
					title = title.gsub(/\//, '\\')
					title = title.gsub(/&#039;/, "'")
					if (options[:verbose] == true)
						puts "emusic: Downloading #{title}"
					end
					open(directory + "/" + title + ".mp3","w").write(open((track/:TRACKURL).inner_html).read) 
				end
				if (options[:verbose] == true)
					puts "emusic: Download complete!"
				end
			else
				puts "emusic: No downloads found in file: #{filename}"
			end

			if options[:remove] == true
				File.delete(filename)
				if (options[:verbose] == true)
					puts "emusic: Removed File #{filename}"
				end
			end
		else
			puts "emusic: File #{filename} not found"
			exit
		end
	end
end

app = EMusic.new(ARGV, STDIN)


