require 'rubygems'
require 'rake'
require 'echoe'
require 'hpricot'
require 'open-uri' 
require 'optparse'

Echoe.new('emusic-downloader', '0.5') do |p|
  p.description    = "Download eMusic .emz files"
  p.url            = "http://nickrowe.info"
  p.author         = "Nicholas Rowe"
  p.email          = "nixterrimus@gmail.com"
  p.ignore_pattern = ["tmp/*", "script/*", "README.textile"]
  p.development_dependencies = []
end

